spring:
  # DataSource Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_rabbitmq_example?useSSL=false&serverTimezone=UTC
    username: root
    password: Xx223322 # If the password is empty, just leave it blank

  # JPA/Hibernate Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # Change to 'update' for production environments
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # RabbitMQ Configuration
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

# Spring Profiles Configuration
profiles:
  active: dev

# Security configurations can also be added here if needed, such as security rules
# security:
#   basic:
#     enabled: true
#   user:
#     name: admin
#     password: admin

# Custom application settings could also be added here
custom:
  feature-x-enabled: true
